#config_version=5

config:
  - coils.yaml
  - displays.yaml
  - hardware.yaml
  - keyboard.yaml
  - lights.yaml
  - slides.yaml
  - switches.yaml

modes:
# base modules
  - base
  - tilt
# game logic
  - gates
  - pops
  - bumpers
  - fixed
  - listener
  - kicker
  - tunnel

#  - service
#  Service is disabled due to an error --
#  mpfmc.core.audio.audio_exception.AudioException: 'sfx' is not a valid track name. Could not create sound 'power_off' asset
